import javax.swing.*;

public class coefficients {
    public JCheckBox airCheckBox;
    public JCheckBox waterCheckBox;
    public JCheckBox cloudCheckBox;
    public JPanel air_c;
    public JTextArea asc;
    public JTextArea aac;
    public JPanel water_c;
    public JPanel cloud_c;
    public JPanel coefficient_content;
    public JTextField indentifierBox;
    public JSlider a_s_b_2;
    public JSlider a_s_g_2;
    public JSlider a_s_r_2;
    public JTextField a_s_r_1;
    public JTextField a_s_g_1;
    public JTextField a_s_b_1;
    public JTextField a_a_r_1;
    public JTextField a_a_g_1;
    public JTextField a_a_b_1;
    public JSlider a_a_r_2;
    public JSlider a_a_g_2;
    public JSlider a_a_b_2;
    public JTextField w_s_r_1;
    public JTextField w_s_g_1;
    public JTextField w_s_b_1;
    public JSlider w_s_r_2;
    public JSlider w_s_g_2;
    public JSlider w_s_b_2;
    public JTextField w_a_r_1;
    public JSlider w_a_r_2;
    public JTextField w_a_g_1;
    public JSlider w_a_g_2;
    public JTextField w_a_b_1;
    public JSlider w_a_b_2;
    public JTextField csr1;
    public JSlider csr2;
    public JTextField csg1;
    public JSlider csg2;
    public JTextField csb1;
    public JSlider csb2;
    public JTextField car1;
    public JSlider car2;
    public JTextField cag1;
    public JSlider cag2;
    public JTextField cab1;
    public JSlider cab2;

    public JTextArea amountOfLightScatteredTextArea;
    public JPanel ascp;
    public JPanel aacp;
    public JPanel wscp;
    public JPanel wacp;
    public JPanel cscp;
    public JPanel cacp;
}
