import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class settingPage {
    public JCheckBox airFogCheckBox;
    public JCheckBox waterFogCheckBox;
    public JCheckBox weatherFogCheckBox;
    public JCheckBox lavaFogCheckBox;
    public JCheckBox lava_ResistanceCheckBox;
    public JPanel air_fog;
    public JComboBox air_fog_4;
    public JTextField air_fog_1;
    public JLabel at1;
    public JLabel at2;
    public JTextField air_fog_2;
    public JComboBox water_fog_4;
    public JTextField water_fog_1;
    public JTextField water_fog_2;
    public JComboBox weather_fog_4;
    public JTextField weather_fog_1;
    public JTextField weather_fog_2;
    public JComboBox lava_fog_4;
    public JTextField lava_fog_1;
    public JTextField lava_fog_2;
    public JComboBox lava_resistance_fog_4;
    public JTextField lava_resistance_fog_1;
    public JTextField lava_resistance_fog_2;
    public JPanel water_fog;
    public JPanel weather_fog;
    public JPanel lava_fog;
    public JPanel lava_resistance_fog;
    public JPanel distance_content;

    public JTextField indentifierBox;

    public JSlider air_fog_3_r;
    public JSlider air_fog_3_g;
    public JSlider air_fog_3_b;
    public JSlider water_fog_3_r;
    public JSlider water_fog_3_g;
    public JSlider water_fog_3_b;
    public JSlider weather_fog_3_r;
    public JSlider weather_fog_3_g;
    public JSlider weather_fog_3_b;
    public JSlider lava_fog_3_r;
    public JSlider lava_fog_3_g;
    public JSlider lava_fog_3_b;
    public JSlider lava_resistance_fog_3_r;
    public JSlider lava_resistance_fog_3_g;
    public JSlider lava_resistance_fog_3_b;
    public JSpinner ar;
    public JSpinner ag;
    public JSpinner ab;
    public JSpinner wr;
    public JSpinner wg;
    public JSpinner wb;
    public JSpinner er;
    public JSpinner eg;
    public JSpinner eb;
    public JSpinner lr;
    public JSpinner lg;
    public JSpinner lb;
    public JSpinner lrr;
    public JSpinner lrg;
    public JSpinner lrb;
    public JTextArea afc;

    public JLabel fogColourLabel1;
    public JButton qr1;
    public JButton qr2;
    public JButton qr3;
    public JButton qr4;
    public JButton qr5;
    public JSlider as1;
    public JSlider as2;
    public JSlider ws1;
    public JSlider ws2;
    public JLabel wt1;
    public JLabel wt2;
    public JButton fileDrop;

    public JPanel wfcp;
    public JPanel afcp;
    public JPanel efcp;
    public JPanel lfcp;
    public JPanel lrcp;
    public JLabel et1;
    public JLabel et2;
    public JLabel lt1;
    public JLabel lt2;
    public JLabel lrt1;
    public JLabel lrt2;
    public JSlider es1;
    public JSlider es2;
    public JSlider ls1;
    public JSlider ls2;
    public JSlider lrs1;
    public JSlider lrs2;
    private JLabel fogColourLabel;
    private JLabel fogColourLabel2;
    private JLabel fogColourLabel3;
    private JLabel fogColourLabel4;
    JScrollPane scrll;
    private JLabel gLabel;
    private JLabel bLabel;
    private JLabel rLabel;
    private JLabel gLabel1;
    private JLabel bLabel1;
    private JLabel rLabel1;
    private JLabel gLabel2;
    private JLabel bLabel2;
    private JLabel rLabel2;
    private JLabel gLabel3;
    private JLabel bLabel3;
    private JLabel rLabel3;
    private JLabel gLabel4;
    private JLabel bLabel4;
    private JLabel rLabel4;

    public void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
