import javax.swing.*;

public class volumetric {
    public JCheckBox airFogCheckBox;
    public JCheckBox waterFogCheckBox;
    public JCheckBox weatherFogCheckBox;
    public JCheckBox lavaFogCheckBox;
    public JCheckBox lava_ResistanceCheckBox;
    public JPanel air_vfog;
    public JTextField air_vfog_1;
    public JCheckBox air_vfog_2;
    public JTextField air_vfog_3;
    public JTextField air_vfog_4;
    public JPanel water_vfog;
    public JTextField water_vfog_1;
    public JCheckBox water_vfog_2;
    public JTextField water_vfog_3;
    public JTextField water_vfog_4;
    public JPanel weather_vfog;
    public JTextField weather_vfog_1;
    public JCheckBox weather_vfog_2;
    public JTextField weather_vfog_3;
    public JTextField weather_vfog_4;
    public JPanel lava_vfog;
    public JTextField lava_vfog_1;
    public JCheckBox lava_vfog_2;
    public JTextField lava_vfog_3;
    public JTextField lava_vfog_4;
    public JPanel lava_resistance_vfog;
    public JTextField lava_resistance_vfog_1;
    public JCheckBox lava_resistance_vfog_2;
    public JTextField lava_resistance_vfog_3;
    public JTextField lava_resistance_vfog_4;
    public JPanel volumetric_content;
    public JSlider a1s;
    public JSlider w1s;
    public JSlider e1s;
    public JSlider l1s;
    public JSlider lr1s;
    public JScrollPane scrll;
    public JTextField indentifierBox;
}
